spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${DB_NAME:webflux-course}
      username: ${USER_DB:admin}
      password: ${PASSWORD_DB}
      auto-index-creation: true
      authentication-database: admin
  application:
    name: webflux-course

      
